tickers:
- symbol: 2002.T
  name: 日清製粉グループ本社
- symbol: 2269.T
  name: 明治ホールディングス
- symbol: 2282.T
  name: 日本ハム
- symbol: 2501.T
  name: サッポロホールディングス
- symbol: 2502.T
  name: アサヒグループホールディングス
- symbol: 2503.T
  name: キリンホールディングス
- symbol: 2801.T
  name: キッコーマン
- symbol: 2802.T
  name: 味の素
- symbol: 2871.T
  name: ニチレイ
- symbol: 2914.T
  name: 日本たばこ産業
- symbol: 3401.T
  name: 帝人
- symbol: 3402.T
  name: 東レ
- symbol: 3861.T
  name: 王子ホールディングス
- symbol: 3405.T
  name: クラレ
- symbol: 3407.T
  name: 旭化成
- symbol: 4004.T
  name: レゾナック・ホールディングス
- symbol: 4005.T
  name: 住友化学
- symbol: 4021.T
  name: 日産化学
- symbol: 4042.T
  name: 東ソー
- symbol: 4043.T
  name: トクヤマ
- symbol: 4061.T
  name: デンカ
- symbol: 4063.T
  name: 信越化学工業
- symbol: 4183.T
  name: 三井化学
- symbol: 4188.T
  name: 三菱ケミカルグループ
- symbol: 4208.T
  name: UBE
- symbol: 4452.T
  name: 花王
- symbol: 4901.T
  name: 富士フイルムホールディングス
- symbol: 4911.T
  name: 資生堂
- symbol: 6988.T
  name: 日東電工
- symbol: 4151.T
  name: 協和キリン
- symbol: 4502.T
  name: 武田薬品工業
- symbol: 4503.T
  name: アステラス製薬
- symbol: 4506.T
  name: 住友ファーマ
- symbol: 4507.T
  name: 塩野義製薬
- symbol: 4519.T
  name: 中外製薬
- symbol: 4523.T
  name: エーザイ
- symbol: 4568.T
  name: 第一三共
- symbol: 4578.T
  name: 大塚ホールディングス
- symbol: 5019.T
  name: 出光興産
- symbol: 5020.T
  name: ENEOSホールディングス
- symbol: 5101.T
  name: 横浜ゴム
- symbol: 5108.T
  name: ブリヂストン
- symbol: 5201.T
  name: AGC
- symbol: 5214.T
  name: 日本電気硝子
- symbol: 5233.T
  name: 太平洋セメント
- symbol: 5301.T
  name: 東海カーボン
- symbol: 5332.T
  name: TOTO
- symbol: 5333.T
  name: 日本碍子
- symbol: 5401.T
  name: 日本製鉄
- symbol: 5406.T
  name: 神戸製鋼所
- symbol: 5411.T
  name: JFEホールディングス
- symbol: 3436.T
  name: SUMCO
- symbol: 5706.T
  name: 三井金属鉱業
- symbol: 5711.T
  name: 三菱マテリアル
- symbol: 5713.T
  name: 住友金属鉱山
- symbol: 5714.T
  name: DOWAホールディングス
- symbol: 5801.T
  name: 古河電気工業
- symbol: 5802.T
  name: 住友電気工業
- symbol: 5803.T
  name: フジクラ
- symbol: 5631.T
  name: 日本製鋼所
- symbol: 6103.T
  name: オークマ
- symbol: 6113.T
  name: アマダ
- symbol: 6273.T
  name: SMC
- symbol: 6301.T
  name: 小松製作所
- symbol: 6302.T
  name: 住友重機械工業
- symbol: 6305.T
  name: 日立建機
- symbol: 6326.T
  name: クボタ
- symbol: 6361.T
  name: 荏原製作所
- symbol: 6367.T
  name: ダイキン工業
- symbol: 6471.T
  name: 日本精工
- symbol: 6472.T
  name: NTN
- symbol: 6473.T
  name: ジェイテクト
- symbol: 7004.T
  name: カナデビア
- symbol: 7011.T
  name: 三菱重工業
- symbol: 7013.T
  name: IHI
- symbol: 4062.T
  name: イビデン
- symbol: 6479.T
  name: ミネベアミツミ
- symbol: 6501.T
  name: 日立製作所
- symbol: 6503.T
  name: 三菱電機
- symbol: 6504.T
  name: 富士電機
- symbol: 6506.T
  name: 安川電機
- symbol: 6526.T
  name: ソシオネクスト
- symbol: 6645.T
  name: オムロン
- symbol: 6674.T
  name: ジーエス・ユアサコーポレーション
- symbol: 6701.T
  name: 日本電気
- symbol: 6702.T
  name: 富士通
- symbol: 6723.T
  name: ルネサスエレクトロニクス
- symbol: 6724.T
  name: セイコーエプソン
- symbol: 6752.T
  name: パナソニックホールディングス
- symbol: 6753.T
  name: シャープ
- symbol: 6758.T
  name: ソニーグループ
- symbol: 6762.T
  name: TDK
- symbol: 6770.T
  name: アルプスアルパイン
- symbol: 6841.T
  name: 横河電機
- symbol: 6857.T
  name: アドバンテスト
- symbol: 6861.T
  name: キーエンス
- symbol: 6902.T
  name: デンソー
- symbol: 6920.T
  name: レーザーテック
- symbol: 6952.T
  name: カシオ計算機
- symbol: 6954.T
  name: ファナック
- symbol: 6963.T
  name: ローム
- symbol: 6971.T
  name: 京セラ
- symbol: 6976.T
  name: 太陽誘電
- symbol: 6981.T
  name: 村田製作所
- symbol: 7735.T
  name: SCREENホールディングス
- symbol: 7751.T
  name: キヤノン
- symbol: 7752.T
  name: リコー
- symbol: 8035.T
  name: 東京エレクトロン
- symbol: 7012.T
  name: 川崎重工業
- symbol: 7201.T
  name: 日産自動車
- symbol: 7202.T
  name: いすゞ自動車
- symbol: 7203.T
  name: トヨタ自動車
- symbol: 7205.T
  name: 日野自動車
- symbol: 7211.T
  name: 三菱自動車工業
- symbol: 7261.T
  name: マツダ
- symbol: 7267.T
  name: 本田技研工業
- symbol: 7269.T
  name: スズキ
- symbol: 7270.T
  name: SUBARU
- symbol: 7272.T
  name: ヤマハ発動機
- symbol: 4543.T
  name: テルモ
- symbol: 4902.T
  name: コニカミノルタ
- symbol: 6146.T
  name: ディスコ
- symbol: 7731.T
  name: ニコン
- symbol: 7733.T
  name: オリンパス
- symbol: 7741.T
  name: HOYA
- symbol: 7832.T
  name: バンダイナムコホールディングス
- symbol: 7911.T
  name: TOPPANホールディングス
- symbol: 7912.T
  name: 大日本印刷
- symbol: 7951.T
  name: ヤマハ
- symbol: 1332.T
  name: ニッスイ
- symbol: 1605.T
  name: INPEX
- symbol: 1721.T
  name: コムシスホールディングス
- symbol: 1801.T
  name: 大成建設
- symbol: 1802.T
  name: 大林組
- symbol: 1803.T
  name: 清水建設
- symbol: 1808.T
  name: 長谷工コーポレーション
- symbol: 1812.T
  name: 鹿島建設
- symbol: 1925.T
  name: 大和ハウス工業
- symbol: 1928.T
  name: 積水ハウス
- symbol: 1963.T
  name: 日揮ホールディングス
- symbol: 2768.T
  name: 双日
- symbol: 8001.T
  name: 伊藤忠商事
- symbol: 8002.T
  name: 丸紅
- symbol: 8015.T
  name: 豊田通商
- symbol: 8031.T
  name: 三井物産
- symbol: 8053.T
  name: 住友商事
- symbol: 8058.T
  name: 三菱商事
- symbol: 3086.T
  name: J.フロント リテイリング
- symbol: 3092.T
  name: ZOZO
- symbol: 3099.T
  name: 三越伊勢丹ホールディングス
- symbol: 3382.T
  name: セブン&アイ・ホールディングス
- symbol: 7453.T
  name: 良品計画
- symbol: 8233.T
  name: 髙島屋
- symbol: 8252.T
  name: 丸井グループ
- symbol: 8267.T
  name: イオン
- symbol: 9843.T
  name: ニトリホールディングス
- symbol: 9983.T
  name: ファーストリテイリング
- symbol: 5831.T
  name: しずおかフィナンシャルグループ
- symbol: 7186.T
  name: 横浜フィナンシャルグループ
- symbol: 8304.T
  name: あおぞら銀行
- symbol: 8306.T
  name: 三菱UFJフィナンシャル・グループ
- symbol: 8308.T
  name: りそなホールディングス
- symbol: 8309.T
  name: 三井住友トラスト・ホールディングス
- symbol: 8316.T
  name: 三井住友フィナンシャルグループ
- symbol: 8331.T
  name: 千葉銀行
- symbol: 8354.T
  name: ふくおかフィナンシャルグループ
- symbol: 8411.T
  name: みずほフィナンシャルグループ
- symbol: 8601.T
  name: 大和証券グループ本社
- symbol: 8604.T
  name: 野村ホールディングス
- symbol: 8630.T
  name: SOMPOホールディングス
- symbol: 8725.T
  name: MS&ADインシュアランスグループホールディングス
- symbol: 8750.T
  name: 第一生命ホールディングス
- symbol: 8766.T
  name: 東京海上ホールディングス
- symbol: 8795.T
  name: T&Dホールディングス
- symbol: 8253.T
  name: クレディセゾン
- symbol: 8591.T
  name: オリックス
- symbol: 8697.T
  name: 日本取引所グループ
- symbol: 3289.T
  name: 東急不動産ホールディングス
- symbol: 8801.T
  name: 三井不動産
- symbol: 8802.T
  name: 三菱地所
- symbol: 8804.T
  name: 東京建物
- symbol: 8830.T
  name: 住友不動産
- symbol: 9001.T
  name: 東武鉄道
- symbol: 9005.T
  name: 東急
- symbol: 9007.T
  name: 小田急電鉄
- symbol: 9008.T
  name: 京王電鉄
- symbol: 9009.T
  name: 京成電鉄
- symbol: 9020.T
  name: 東日本旅客鉄道
- symbol: 9021.T
  name: 西日本旅客鉄道
- symbol: 9022.T
  name: 東海旅客鉄道
- symbol: 9064.T
  name: ヤマトホールディングス
- symbol: 9147.T
  name: NIPPON EXPRESSホールディングス
- symbol: 9101.T
  name: 日本郵船
- symbol: 9104.T
  name: 商船三井
- symbol: 9107.T
  name: 川崎汽船
- symbol: 9201.T
  name: 日本航空
- symbol: 9202.T
  name: ANAホールディングス
- symbol: 9432.T
  name: NTT
- symbol: 9433.T
  name: KDDI
- symbol: 9434.T
  name: ソフトバンク
- symbol: 9984.T
  name: ソフトバンクグループ
- symbol: 9501.T
  name: 東京電力ホールディングス
- symbol: 9502.T
  name: 中部電力
- symbol: 9503.T
  name: 関西電力
- symbol: 9531.T
  name: 東京ガス
- symbol: 9532.T
  name: 大阪ガス
- symbol: 2413.T
  name: エムスリー
- symbol: 2432.T
  name: ディー・エヌ・エー
- symbol: 3659.T
  name: ネクソン
- symbol: 3697.T
  name: SHIFT
- symbol: 4307.T
  name: 野村総合研究所
- symbol: 4324.T
  name: 電通グループ
- symbol: 4385.T
  name: メルカリ
- symbol: 4661.T
  name: オリエンタルランド
- symbol: 4689.T
  name: LINEヤフー
- symbol: 4704.T
  name: トレンドマイクロ
- symbol: 4751.T
  name: サイバーエージェント
- symbol: 4755.T
  name: 楽天
- symbol: 6098.T
  name: リクルートホールディングス
- symbol: 6178.T
  name: 日本郵政
- symbol: 6532.T
  name: ベイカレント
- symbol: 7974.T
  name: 任天堂
- symbol: 9602.T
  name: 東宝
- symbol: 9735.T
  name: セコム
- symbol: 9766.T
  name: コナミグループ
